/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hanoigui;



import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author omar
 */
public class TorreHanoi extends javax.swing.JPanel {
    private Image imagen;
    private int[] discos;
    /**
     * Creates new form DiscosHanoi
     */
    public TorreHanoi() {
        initComponents();
        this.setLayout(new BoxLayout(this,BoxLayout.PAGE_AXIS));
        //this.setLayout(new BorderLayout());
        //setImagen("torre.png");
      
        
    }
    
    public void setDiscos(int[] discos){
        this.discos=discos;
        this.removeAll();
        for(int i=discos.length-1;i>=0;i--){
        if(discos[i]!=0){
            JButton b=new JButton(""+discos[i]);
            b.setAlignmentX(CENTER_ALIGNMENT);
            //b.setAlignmentY(BOTTOM_ALIGNMENT);
            b.setText(rayitas(discos[i]));
            
            this.add(b);
            repaint();
        }
        
        }
    }
    public String rayitas(int n){
        String s="";
        for(int i=0;i<n;i++){
        s+="__";
        }
    return s;
    }
    
    public void setImagen(String nombreImagen){
        imagen = new ImageIcon(
                   getClass().getResource(nombreImagen)
                   ).getImage();
    }
    @Override
    public void paint(Graphics g) {
        g.drawImage(imagen, 0, 0, getWidth(), getHeight(),
                        this);
 
        setOpaque(false);
        super.paint(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
