/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hanoigui;

import java.awt.BorderLayout;
import static java.awt.Component.CENTER_ALIGNMENT;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.BoxLayout;
import javax.swing.JButton;

/**
 *
 * @author omar
 */
public class Torres extends javax.swing.JFrame {
    //private TorreHanoi[] torres;
    /**
     * Creates new form Torres
     */
    private String datos;
    private int[] numeros;
    private int pasos;
    private String nombreArchivo;
    private int indice;
    private int discos;
    private boolean ended;
    
    public Torres(String archivo) {
        initComponents();
        nombreArchivo=archivo;
    try{        
        datos=leeArchivo(nombreArchivo);}catch(Exception e){System.out.println("Error al leer el archivo");}
        numeros=StringToIntArray(datos);
        pasos=0;
        indice=0;
        discos=numeros[0];
        ended=false;
        //torres=new TorreHanoi[3];
        
   
        
    }
    
    
    public void setDiscos(){
     int[] x={3,2,0};
                this.setDiscos(torreHanoi1,x);
                repaint();
    }
    
      public void setDiscos(TorreHanoi t, int[] discos){
        t.removeAll();
        for(int i=discos.length-1;i>=0;i--){
        if(discos[i]!=0){
            JButton b=new JButton(""+discos[i]);
            b.setAlignmentX(CENTER_ALIGNMENT);
            b.setAlignmentY(TOP_ALIGNMENT);
            b.setText(t.rayitas(discos[i]));
            t.setLayout(new BoxLayout(t, BoxLayout.Y_AXIS));
            t.add(b);
            repaint();
        }
        
        }
    }
    
    public void setDiscos(int nDiscos, int[] datos){
        TorreHanoi[] torres = {torreHanoi1,torreHanoi2,torreHanoi3};
        int t=0;
        int[] numeros=new int[nDiscos];
        for(int d=0;d<3;d++){
         for(int i=0;i<nDiscos;i++){
             numeros[i]=datos[t];
             t++;    
             System.out.print(numeros[i]);
         }
         setDiscos(torres[d],numeros);
         System.out.print("\n");
        }
    }
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        torreHanoi1 = new hanoigui.TorreHanoi();
        torreHanoi2 = new hanoigui.TorreHanoi();
        torreHanoi3 = new hanoigui.TorreHanoi();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 157, 136));
        setForeground(new java.awt.Color(56, 30, 119));

        torreHanoi1.setLayout(new javax.swing.BoxLayout(torreHanoi1, javax.swing.BoxLayout.LINE_AXIS));

        torreHanoi2.setLayout(new javax.swing.BoxLayout(torreHanoi2, javax.swing.BoxLayout.LINE_AXIS));

        torreHanoi3.setLayout(new javax.swing.BoxLayout(torreHanoi3, javax.swing.BoxLayout.LINE_AXIS));

        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Borrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Atras");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("0");

        jLabel2.setText("Pasos transcurridos:");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel3.setText("TORRES DE HANOI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(torreHanoi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(torreHanoi2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(torreHanoi3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                    .addComponent(jLabel1))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(torreHanoi3, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(torreHanoi2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(torreHanoi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       siguiente();
       pasos();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void pasos(){
        jLabel1.setText(""+pasos);
    }
    public void siguiente(){
    if(indice>=numeros.length){
        indice=0;
        pasos=0;
    }
        int[] datos1=new int[discos];
        int[] datos2=new int[discos];
        int[] datos3=new int[discos];
        for(int i=0; i<discos;i++){
            datos1[i]=numeros[indice+i];
            datos2[i]=numeros[indice+discos+i];
            datos3[i]=numeros[indice+(2*discos)+i];
        }
        indice=indice+(3*discos);
        pasos++;
        /*this.setDiscos(torreHanoi1,datos1);
        this.setDiscos(torreHanoi2,datos2);
        this.setDiscos(torreHanoi3,datos3);*/
        setDiscos(torreHanoi1,datos1);
        setDiscos(torreHanoi2,datos2);
        setDiscos(torreHanoi3,datos3);
        this.validate();
    }
    
    public void atras(){
        indice=indice-(6*discos);
        pasos--;
        if(indice<0){
            borrar();
            
        }
        int[] datos1=new int[discos];
        int[] datos2=new int[discos];
        int[] datos3=new int[discos];
        for(int i=0; i<discos;i++){
            datos1[i]=numeros[indice+i];
            datos2[i]=numeros[indice+discos+i];
            datos3[i]=numeros[indice+(2*discos)+i];
        }
        indice=indice+(3*discos);
        /*this.setDiscos(torreHanoi1,datos1);
        this.setDiscos(torreHanoi2,datos2);
        this.setDiscos(torreHanoi3,datos3);*/
        setDiscos(torreHanoi1,datos1);
        setDiscos(torreHanoi2,datos2);
        setDiscos(torreHanoi3,datos3);
        this.validate();
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        borrar();
        pasos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        atras();
        pasos();
    }//GEN-LAST:event_jButton3ActionPerformed

    public void borrar(){
    torreHanoi1.removeAll();
    torreHanoi2.removeAll();
    torreHanoi3.removeAll();
    indice=0;
    pasos=0;
    this.repaint();
    }
 

    public String leeArchivo(String nombreArchivo) throws FileNotFoundException, IOException {
      String cadena="";
      String s="";
      FileReader f = new FileReader(nombreArchivo);
      BufferedReader b = new BufferedReader(f);
      String tipo=b.readLine();
      System.out.println(tipo);
      discos=Integer.parseInt(b.readLine());
      System.out.println(discos);
      cadena = b.readLine();
          System.out.println(cadena);
          
      
      b.close();
      if (tipo.equals("profundidad")){
         
          cadena=normalizaTexto(cadena);
           System.out.println(cadena);
      }
      
      return cadena;
}
    
    public String normalizaTexto(String e){
    String s="";
    char[] c=e.toCharArray();
    //invertir cadena
    for(int i=1;i<=c.length;i++){
        s+=c[c.length-i];
    }
    
    c=s.toCharArray();
    s="";
    int salto=3*discos;
    int puntero=0;
    for(int i=0;i<c.length;i+=salto){
      for(int x=1,d=0;d<discos;d++,x++){
          for(int j=i+discos-x;j<i+salto;j+=discos){
            s+=c[j];
          }
      }
      }
   
    System.out.print("textoNormalizado: \n"+s);
    return s;
    }
    
     public int[] StringToIntArray(String s){
        char[] c=s.toCharArray();
        int[] enteros=new int[c.length];
        for(int i=0;i<c.length;i++){
            enteros[i]=Integer.parseInt(""+c[i]);
        }
      
        return enteros;
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private hanoigui.TorreHanoi torreHanoi1;
    private hanoigui.TorreHanoi torreHanoi2;
    private hanoigui.TorreHanoi torreHanoi3;
    // End of variables declaration//GEN-END:variables
}
