/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentecompuesto;

import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author omar
 */
public class textoConEtiquetas extends javax.swing.JPanel {

    /**
     * Creates new form labelAndText
     */
    private String[] cuatroEtiquetas; 
    
    public textoConEtiquetas() {
        initComponents();
        etiquetaArriba.setVisible(false);
        etiquetaDerecha.setVisible(false);
        etiquetaAbajo.setVisible(false);
        etiquetaIzquierda.setVisible(false);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        campoTexto1 = new componentedatos.CampoTexto();
        etiquetaArriba = new javax.swing.JLabel();
        etiquetaDerecha = new javax.swing.JLabel();
        etiquetaAbajo = new javax.swing.JLabel();
        etiquetaIzquierda = new javax.swing.JLabel();

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        campoTexto1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoTexto1KeyTyped(evt);
            }
        });

        etiquetaArriba.setText("jLabel1");

        etiquetaDerecha.setText("jLabel2");

        etiquetaAbajo.setText("jLabel3");

        etiquetaIzquierda.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etiquetaIzquierda)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(etiquetaArriba))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(etiquetaDerecha)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(etiquetaAbajo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(etiquetaArriba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaDerecha)
                    .addComponent(etiquetaIzquierda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaAbajo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void formKeyTyped(java.awt.event.KeyEvent evt) {                              
        
    }                             

    public void setEtiquetaArriba(String t){
        if(t.equals("")){
            etiquetaArriba.setVisible(false);
            etiquetaArriba.setText(t);
        }else{
            etiquetaArriba.setVisible(true);
            etiquetaArriba.setText(t);
        }
    }
    public void setEtiquetaDerecha(String t){
     if(t.equals("")){
            etiquetaDerecha.setVisible(false);
            etiquetaDerecha.setText(t);
        }else{
            etiquetaDerecha.setVisible(true);
            etiquetaDerecha.setText(t);
        }
    }
    public void setEtiquetaAbajo(String t){
         if(t.equals("")){
            etiquetaAbajo.setVisible(false);
            etiquetaAbajo.setText(t);
        }else{
            etiquetaAbajo.setVisible(true);
            etiquetaAbajo.setText(t);
        }
    
    }
    public void setEtiquetaIzquierda(String t){
         if(t.equals("")){
            etiquetaIzquierda.setVisible(false);
            etiquetaIzquierda.setText(t);
        }else{
            etiquetaIzquierda.setVisible(true);
            etiquetaIzquierda.setText(t);
        }
    
    }
    
    public void setCuatroEtiquetas(String[] s){
        cuatroEtiquetas=s;
       
        for(int i=0;i<4;i++){

            switch(i){
                case 0: setEtiquetaArriba(cuatroEtiquetas[i]);
                break;
                case 1: setEtiquetaDerecha(cuatroEtiquetas[i]);
                break;
                case 2: setEtiquetaAbajo(cuatroEtiquetas[i]);
                break;
                case 3: setEtiquetaIzquierda(cuatroEtiquetas[i]);
                break;
            }

        }
       

   }
    
    
    
    
    private void campoTexto1KeyTyped(java.awt.event.KeyEvent evt) {                                     
    }                                    


    // Variables declaration - do not modify                     
    private componentedatos.CampoTexto campoTexto1;
    private javax.swing.JLabel etiquetaArriba;
    private javax.swing.JLabel etiquetaDerecha;
    private javax.swing.JLabel etiquetaAbajo;
    private javax.swing.JLabel etiquetaIzquierda;
    // End of variables declaration                   
}
